### ISSUE TITLE
Ability to conditionally set/nullify `external_location`?

### ISSUE THREAD

**Issue by aaronsteers** [jwills/dbt-duckdb#116]
I'm working on a PR where we may want to have the option to _either_ import raw data _or_ load from seed files.

Is it possible to return a value in `external_location` that nullifies the expression?

Something like the psuedocode:

```
external_location: "{{ if {some value set} then {a real external location} else null }}"
```

Where in this case `null` would be intepreted as no instruction.

The alternative is to ask users to comment and uncomment the value, e.g.:

```yml
    # Uncomment these lines if you want to use the pregenerated seed files:
    # meta:
    #   external_location: "read_csv_auto('./jaffle-data/{name}.csv', header=1)"
```

https://github.com/MeltanoLabs/jaffle-shop-template/pull/1/files#diff-6c181d0ccc3c5e37e2feaacdd8872e09073b138835156160dcb5ee7c159f8c63L3-R9

**Comment by jwills** [comment]
Yeah, my understanding (which I would be grateful if you would confirm for me) is that you can treat everything in one of dbt's `.yml` files as if it was jinja-fied as well, including meta tags on sources. So in your example, something like:

```
meta:
  external_location: "{{ \"read_csv_auto('./jaffle-data/{name}.csv', header=1)\" if some_value is not none }}"
```

...should return an empty string as the value of the `external_location` property if `some_value` is `None`. If the value of the `external_location` is an empty string, then `this condition`(https://github.com/jwills/dbt-duckdb/blob/master/dbt/adapters/duckdb/relation.py#L29) will evaluate to false, and we would fall back to using the standard dbt strategy for rendering the source table as a relation in the model.

(Note the fact that any field in a `sources.yml` file may be treated as a jinja template is exactly why we use f-string style formatting for the `name` and `identifier` in external sources.)

**Comment by aaronsteers** [comment]
Great, thanks @jwills !

I'll close for now and reopen if I run into any issue. 

Also, will post back here when I see confirmation either way. 👍

**Comment by aaronsteers** [comment]
@jwills - Circling back.

These both work:

```yml
external_location: null  # Works!
external_location: ''  # Works!
```

However, when calculating with jinja, I could't get null working, so I went with returning an empty string.

```yml
      external_location: >-
        {{ None if env_var('JAFFLE_RAW_SCHEMA', '') else 'read_csv_auto("./jaffle-data/{name}.csv", header=1)' }}
```

I used the `>-` yaml operator which (1) let's me put the string on the next line for readability, (2) reduces string escaping I need to do, and (3) doesn't add any preceeding or post-fixed newlines.

**Comment by jwills** [comment]
@aaronsteers that is good to here, I'll add a section about this situation (which I expect to be more common in the future) when I update the docs this week.

Wanted to clarify one thing tho: does this not work?

```
sources:
  - name: ecom
    schema: "{{ env_var('JAFFLE_RAW_SCHEMA', 'jaffle_raw') }}"
    description: E-commerce data
    meta:
      # If `$JAFFLE_RAW_SCHEMA` is specified, use the provided raw data. Otherwise, use the csv seed data from the repo.
      external_location: >-
        {{ 'read_csv_auto("./jaffle-data/{name}.csv", header=1)' if not env_var('JAFFLE_RAW_SCHEMA', '') }}
```
