### ISSUE TITLE
External Location: f-string value needs more than one variable

### ISSUE THREAD

**Issue by armsepehr** [jwills/dbt-duckdb#127]
I am interested in using external_location f-string with several variable but only `name`, `indicator` and `schema` are known in the f-string.  

```
sources:
  - name: external_source
    meta:
      external_location: "s3://my-bucket/{folder2}/{name}.{suffix}"
    tables:
      - name: source1
         suffix: parquet
         folder: folder1
      - name: source2
        suffix: csv
        folder: folder2
```

Additionally, I don't want to overwrite the external_location for each table name.
