### ISSUE TITLE
Allow arbitrary extensions

### ISSUE THREAD

**Issue by davidgasquez** [jwills/dbt-duckdb#157]
Would be cool to be able to install third party extensions like [`duckdb-python-udf`](https://github.com/MarkRoddy/duckdb-python-udf) from `dbt-duckdb`. Perhaps something like this?

```yml
default:
  outputs:
    dev:
      type: duckdb
      path: /tmp/dbt.duckdb
      extensions:
        - httpfs
        - parquet
        - python_udf@net.ednit.duckdb-extensions.s3.us-west-2.amazonaws.com
```
