### ISSUE TITLE
Plugin SourceConfig returning column metadata

### ISSUE THREAD

**Issue by iamrobo** [jwills/dbt-duckdb#237]
I'm trying to make use of the column property in the Source.Table resource type within a custom plugin. Is there a way to access these from a plugin, or will I need to extend the [SourceConfig](https://github.com/jwills/dbt-duckdb/blob/fb29773573d5fc633cda6991c260d7ad9b476922/dbt/adapters/duckdb/utils.py#L14) class? 

The use case is that I have zipped csv's that do not have column names, and I'd like to load them 

Below is an example of the source.yml file.
```
version: 2
sources:
  - name: source_system
    schema: main
    config:
      plugin: zip
      save_mode: ignore
    tables:
      - name: allowance
        identifier: allowance_{{ var('date')}}
        columns:
          - name: Allow_Company
            data_type: text
          - name: Allow_Pointer
            data_type: text
```
