### ISSUE TITLE
S3 reading error "No files found that match the pattern"

### ISSUE THREAD

**Issue by lassebenni** [jwills/dbt-duckdb#78]
Hi! 

I am trying to read a parquet file from S3 by following the documentation, but for some reason I cannot seem to get it to work..

I am using `dbt-duckdb==1.3.4`.

When trying to read a parquet file from S3 running `dbt build` I get:
```
20:28:45    IO Error: No files found that match the pattern "s3://my-bucket/my-project/data.parquet" 
20:28:45  
20:28:45  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=
```

The `s3://my-bucket/my-project/data.parquet` is just a dummy string obviously, but I do have a Bucket with a parquet file in there which I replace with the actual string for testing.

What I did:

First I set the `S3_ACCESS_KEY_ID` and `S3_SECRET_ACCESS_KEY` environment variables, which are correct and working.

Then I have this in my `profiles.yml`:

```
my_dbt_project:
  outputs:
    dev:
      type: duckdb
      path: ":memory:"
    extensions:
      - httpfs
      - parquet
    settings:
      s3_region: eu-west-1
      s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
      s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"
  target: dev
```

And this in `sources.yml`:

```
 version: 2

sources:
  - name: external_source
    meta:
      external_location: "s3://my-bucket/my-project/data.parquet"
    tables:
      - name: my_table
```

and trying to run this

```
select * from {{ source("external_source", "my_table") }}
```

But it keeps saying it cannot find the file. I tried to specify the `external_root` in `profiles.yml` but no luck..

Any ideas what I am missing.
